using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Meridian.Mapping.Generators;

/// <summary>
/// Roslyn incremental source generator. For each consumer class annotated
/// with <c>[GenerateMapper(typeof(TSrc), typeof(TDst))]</c>, emits a
/// <c>partial</c> class body containing a typed
/// <c>public static TDst MapTo{TDst}(TSrc source)</c> method whose body
/// is a direct property-assignment block.
/// </summary>
/// <remarks>
/// <para>
/// This generator covers the "simple ForMember+MapFrom" subset only —
/// same-name or explicit-attribute property mapping. Anything more
/// complex (resolvers, converters, conditions, recursive graphs) should
/// stay on the runtime <see cref="IMapper"/> path. The goal is to offer
/// an AOT-safe, zero-reflection fast path for the hot types without
/// trying to subsume the whole runtime API.
/// </para>
/// <para>
/// Output is deterministic — property assignments are emitted in the
/// order they appear in the destination type's metadata, not a hashed
/// order — so diffs across generator runs only appear when the
/// destination type actually changes.
/// </para>
/// </remarks>
[Generator(LanguageNames.CSharp)]
public sealed class MeridianMapperGenerator : IIncrementalGenerator
{
    private const string AttributeNamespace = "Meridian.Mapping";
    private const string AttributeName = "GenerateMapperAttribute";
    private const string AttributeFullName = AttributeNamespace + "." + AttributeName;
    private const string DiagnosticCategory = "Meridian.Mapping.Generators";
    private const string AttributeSource = @"// <auto-generated/>
#nullable enable
namespace Meridian.Mapping
{
    /// <summary>
    /// Marks a partial class as the target for a Meridian source-generated
    /// mapper. For each attribute on the class, the generator emits a
    /// typed <c>MapTo{TDestination}(TSource)</c> method inside the class.
    /// </summary>
    /// <remarks>
    /// Only the simple property-to-property mapping subset is supported
    /// at the source-gen level today. Types that need resolvers,
    /// converters, or conditions must use the runtime <c>IMapper</c> API.
    /// </remarks>
    [System.AttributeUsage(System.AttributeTargets.Class, AllowMultiple = true, Inherited = false)]
    internal sealed class GenerateMapperAttribute : System.Attribute
    {
        public GenerateMapperAttribute(System.Type sourceType, System.Type destinationType)
        {
            SourceType = sourceType;
            DestinationType = destinationType;
        }

        public System.Type SourceType { get; }
        public System.Type DestinationType { get; }
    }
}
";

    private static readonly DiagnosticDescriptor NestedContainerMustBePartial = new(
        id: "MERIDIANGEN001",
        title: "Nested mapper containers require partial containing types",
        messageFormat: "Meridian mapper container '{0}' is nested inside non-partial containing type '{1}'. Mark every containing type partial or move the mapper container to namespace scope.",
        category: DiagnosticCategory,
        defaultSeverity: DiagnosticSeverity.Warning,
        isEnabledByDefault: true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // 1. Emit the attribute into the consumer's compilation so they
        //    don't have to reference anything extra beyond Meridian.Mapping.
        context.RegisterPostInitializationOutput(pi =>
            pi.AddSource("GenerateMapperAttribute.g.cs", SourceText.From(AttributeSource, Encoding.UTF8)));

        // 2. Find every class declared partial that carries the attribute.
        var candidates = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeFullName,
                predicate: static (node, _) => node is ClassDeclarationSyntax c
                    && c.Modifiers.Any(m => m.IsKind(Microsoft.CodeAnalysis.CSharp.SyntaxKind.PartialKeyword)),
                transform: static (ctx, _) => ExtractMapperTarget(ctx))
            .Where(static t => t is not null)
            .Select(static (t, _) => t!);

        // 3. Per candidate, emit the partial class body.
        context.RegisterSourceOutput(candidates, static (spc, target) => Emit(spc, target));
    }

    private static MapperTarget? ExtractMapperTarget(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol classSymbol)
            return null;

        var pairs = new List<(ITypeSymbol Source, ITypeSymbol Dest)>();
        foreach (var attr in ctx.Attributes)
        {
            if (attr.ConstructorArguments.Length != 2) continue;

            var src = attr.ConstructorArguments[0].Value as ITypeSymbol;
            var dst = attr.ConstructorArguments[1].Value as ITypeSymbol;
            if (src is null || dst is null) continue;

            pairs.Add((src, dst));
        }

        if (pairs.Count == 0) return null;

        var containingTypes = GetContainingTypes(classSymbol)
            .Select(CreateTypeDeclarationInfo)
            .ToImmutableArray();

        Diagnostic? diagnostic = null;
        var nonPartialContainer = containingTypes.FirstOrDefault(t => !t.IsPartial);
        if (nonPartialContainer is not null)
        {
            diagnostic = Diagnostic.Create(
                NestedContainerMustBePartial,
                classSymbol.Locations.FirstOrDefault(),
                classSymbol.ToDisplayString(SymbolDisplayFormat.CSharpErrorMessageFormat),
                nonPartialContainer.DisplayName);
        }

        return new MapperTarget(
            Namespace: classSymbol.ContainingNamespace.IsGlobalNamespace
                ? null
                : classSymbol.ContainingNamespace.ToDisplayString(),
            ContainingTypes: containingTypes,
            TargetType: CreateTypeDeclarationInfo(classSymbol),
            MetadataPath: BuildMetadataPath(classSymbol),
            Pairs: pairs.ToImmutableArray(),
            Diagnostic: diagnostic);
    }

    private static void Emit(SourceProductionContext spc, MapperTarget target)
    {
        if (target.Diagnostic is not null)
        {
            spc.ReportDiagnostic(target.Diagnostic);
            return;
        }

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        var usings = new SortedSet<string>(StringComparer.Ordinal);
        foreach (var (src, dst) in target.Pairs)
        {
            if (src.ContainingNamespace is { IsGlobalNamespace: false } srcNs)
                usings.Add(srcNs.ToDisplayString());
            if (dst.ContainingNamespace is { IsGlobalNamespace: false } dstNs)
                usings.Add(dstNs.ToDisplayString());
        }

        foreach (var u in usings)
            sb.AppendLine($"using {u};");
        if (usings.Count > 0)
            sb.AppendLine();

        var indent = "";
        if (target.Namespace is not null)
        {
            sb.Append("namespace ").Append(target.Namespace).AppendLine();
            sb.AppendLine("{");
            indent = "    ";
        }

        foreach (var containingType in target.ContainingTypes)
        {
            EmitTypeDeclarationOpen(sb, indent, containingType);
            indent += "    ";
        }

        EmitTypeDeclarationOpen(sb, indent, target.TargetType);
        indent += "    ";

        foreach (var (src, dst) in target.Pairs)
        {
            EmitMapMethod(sb, indent, src, dst);
            sb.AppendLine();
        }

        indent = indent.Substring(0, indent.Length - 4);
        EmitTypeDeclarationClose(sb, indent);

        for (var i = target.ContainingTypes.Length - 1; i >= 0; i--)
        {
            indent = indent.Substring(0, indent.Length - 4);
            EmitTypeDeclarationClose(sb, indent);
        }

        if (target.Namespace is not null)
            sb.AppendLine("}");

        var hint = SanitizeHintName(target.MetadataPath) + ".Meridian.g.cs";
        spc.AddSource(hint, SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static void EmitTypeDeclarationOpen(StringBuilder sb, string indent, TypeDeclarationInfo typeInfo)
    {
        sb.Append(indent);

        if (!string.IsNullOrWhiteSpace(typeInfo.Accessibility))
        {
            sb.Append(typeInfo.Accessibility).Append(' ');
        }

        if (!string.IsNullOrWhiteSpace(typeInfo.Modifiers))
        {
            sb.Append(typeInfo.Modifiers).Append(' ');
        }

        sb.Append("partial ")
            .Append(typeInfo.Keyword)
            .Append(' ')
            .Append(typeInfo.Name)
            .Append(typeInfo.TypeParameters)
            .AppendLine();

        foreach (var clause in typeInfo.ConstraintClauses)
        {
            sb.Append(indent).Append("    ").Append("where ").AppendLine(clause);
        }

        sb.Append(indent).AppendLine("{");
    }

    private static void EmitTypeDeclarationClose(StringBuilder sb, string indent)
    {
        sb.Append(indent).AppendLine("}");
    }

    private static void EmitMapMethod(StringBuilder sb, string indent, ITypeSymbol src, ITypeSymbol dst)
    {
        var srcFull = src.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var dstFull = dst.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var methodSuffix = dst.Name;

        sb.Append(indent).Append("/// <summary>Source-generated mapper emitted by Meridian. Maps ")
            .Append(src.Name).Append(" to ").Append(dst.Name).AppendLine(".</summary>");
        sb.Append(indent).Append("public static ").Append(dstFull)
            .Append(" MapTo").Append(methodSuffix).Append('(').Append(srcFull).AppendLine(" source)");
        sb.Append(indent).AppendLine("{");
        sb.Append(indent).AppendLine("    if (source is null) return default!;");
        sb.Append(indent).Append("    var result = new ").Append(dstFull).AppendLine("();");

        var srcProps = GetWritableNameLookup(src, forWriting: false);
        var dstProps = GetWritableNameLookup(dst, forWriting: true);

        var matched = 0;
        foreach (var dstProp in dstProps.Values)
        {
            if (!srcProps.TryGetValue(dstProp.Name, out var srcProp)) continue;

            if (!SymbolEqualityComparer.Default.Equals(srcProp.Type, dstProp.Type))
            {
                // Only simple same-type assignment in MVP. Emit a diagnostic
                // comment so users know this destination member is unmapped
                // and why, without failing the build.
                sb.Append(indent).Append("    // Skipped: ").Append(dstProp.Name)
                    .Append(" — source is ").Append(srcProp.Type.ToDisplayString())
                    .Append(", destination is ").Append(dstProp.Type.ToDisplayString())
                    .AppendLine(". Use runtime IMapper for type conversion.");
                continue;
            }

            sb.Append(indent).Append("    result.").Append(dstProp.Name)
                .Append(" = source.").Append(srcProp.Name).AppendLine(";");
            matched++;
        }

        if (matched == 0)
        {
            sb.Append(indent).AppendLine("    // No matching properties between source and destination.");
        }

        sb.Append(indent).AppendLine("    return result;");
        sb.Append(indent).AppendLine("}");
    }

    private static Dictionary<string, IPropertySymbol> GetWritableNameLookup(ITypeSymbol type, bool forWriting)
    {
        var result = new Dictionary<string, IPropertySymbol>(StringComparer.Ordinal);
        foreach (var member in type.GetMembers())
        {
            if (member is not IPropertySymbol prop) continue;
            if (prop.IsIndexer) continue;
            if (prop.IsStatic) continue;
            if (prop.DeclaredAccessibility != Accessibility.Public) continue;
            if (forWriting && prop.SetMethod is null) continue;
            if (forWriting && prop.SetMethod!.DeclaredAccessibility != Accessibility.Public) continue;
            if (!forWriting && prop.GetMethod is null) continue;
            if (!forWriting && prop.GetMethod!.DeclaredAccessibility != Accessibility.Public) continue;

            // First declaration wins if a property is somehow doubled.
            if (!result.ContainsKey(prop.Name))
                result[prop.Name] = prop;
        }

        return result;
    }

    private static IEnumerable<INamedTypeSymbol> GetContainingTypes(INamedTypeSymbol symbol)
    {
        var stack = new Stack<INamedTypeSymbol>();
        for (var current = symbol.ContainingType; current is not null; current = current.ContainingType)
        {
            stack.Push(current);
        }

        return stack;
    }

    private static TypeDeclarationInfo CreateTypeDeclarationInfo(INamedTypeSymbol typeSymbol)
    {
        return new TypeDeclarationInfo(
            Name: typeSymbol.Name,
            DisplayName: typeSymbol.ToDisplayString(SymbolDisplayFormat.CSharpErrorMessageFormat),
            Accessibility: GetAccessibility(typeSymbol),
            Keyword: GetTypeKeyword(typeSymbol),
            Modifiers: GetTypeModifiers(typeSymbol),
            TypeParameters: BuildTypeParameters(typeSymbol),
            ConstraintClauses: BuildConstraintClauses(typeSymbol),
            IsPartial: IsPartial(typeSymbol));
    }

    private static string BuildMetadataPath(INamedTypeSymbol symbol)
    {
        var parts = new Stack<string>();
        for (var current = symbol; current is not null; current = current.ContainingType)
        {
            parts.Push(current.MetadataName);
        }

        if (!symbol.ContainingNamespace.IsGlobalNamespace)
        {
            parts.Push(symbol.ContainingNamespace.ToDisplayString());
        }

        return string.Join(".", parts);
    }

    private static string SanitizeHintName(string metadataPath)
    {
        var sb = new StringBuilder(metadataPath.Length);
        foreach (var c in metadataPath)
        {
            sb.Append(char.IsLetterOrDigit(c) || c is '.' or '_' ? c : '_');
        }

        return sb.ToString();
    }

    private static bool IsPartial(INamedTypeSymbol typeSymbol)
    {
        return typeSymbol.DeclaringSyntaxReferences.Any(reference =>
            reference.GetSyntax() is TypeDeclarationSyntax typeDeclaration &&
            typeDeclaration.Modifiers.Any(modifier =>
                modifier.IsKind(Microsoft.CodeAnalysis.CSharp.SyntaxKind.PartialKeyword)));
    }

    private static string GetAccessibility(INamedTypeSymbol typeSymbol)
    {
        return typeSymbol.DeclaredAccessibility switch
        {
            Accessibility.Public => "public",
            Accessibility.Internal => "internal",
            Accessibility.Private => "private",
            Accessibility.Protected => "protected",
            Accessibility.ProtectedOrInternal => "protected internal",
            Accessibility.ProtectedAndInternal => "private protected",
            _ => "internal",
        };
    }

    private static string GetTypeKeyword(INamedTypeSymbol typeSymbol)
    {
        if (typeSymbol.IsRecord)
        {
            return typeSymbol.TypeKind == TypeKind.Struct ? "record struct" : "record class";
        }

        return typeSymbol.TypeKind switch
        {
            TypeKind.Class => "class",
            TypeKind.Struct => "struct",
            TypeKind.Interface => "interface",
            _ => "class",
        };
    }

    private static string GetTypeModifiers(INamedTypeSymbol typeSymbol)
    {
        var modifiers = new List<string>();

        if (typeSymbol.IsStatic)
        {
            modifiers.Add("static");
        }
        else
        {
            if (typeSymbol.TypeKind == TypeKind.Struct && typeSymbol.IsRefLikeType)
            {
                modifiers.Add("ref");
            }

            if (typeSymbol.TypeKind == TypeKind.Struct && typeSymbol.IsReadOnly)
            {
                modifiers.Add("readonly");
            }

            if (typeSymbol.TypeKind == TypeKind.Class && typeSymbol.IsAbstract && !typeSymbol.IsSealed)
            {
                modifiers.Add("abstract");
            }

            if (typeSymbol.TypeKind == TypeKind.Class && typeSymbol.IsSealed)
            {
                modifiers.Add("sealed");
            }
        }

        return string.Join(" ", modifiers);
    }

    private static string BuildTypeParameters(INamedTypeSymbol typeSymbol)
    {
        return typeSymbol.TypeParameters.Length == 0
            ? ""
            : "<" + string.Join(", ", typeSymbol.TypeParameters.Select(tp => tp.Name)) + ">";
    }

    private static ImmutableArray<string> BuildConstraintClauses(INamedTypeSymbol typeSymbol)
    {
        if (typeSymbol.TypeParameters.Length == 0)
        {
            return ImmutableArray<string>.Empty;
        }

        var builder = ImmutableArray.CreateBuilder<string>();
        foreach (var typeParameter in typeSymbol.TypeParameters)
        {
            var parts = new List<string>();

            if (typeParameter.HasReferenceTypeConstraint)
            {
                parts.Add(typeParameter.ReferenceTypeConstraintNullableAnnotation == NullableAnnotation.Annotated
                    ? "class?"
                    : "class");
            }

            if (typeParameter.HasNotNullConstraint)
            {
                parts.Add("notnull");
            }

            if (typeParameter.HasUnmanagedTypeConstraint)
            {
                parts.Add("unmanaged");
            }
            else if (typeParameter.HasValueTypeConstraint)
            {
                parts.Add("struct");
            }

            foreach (var constraintType in typeParameter.ConstraintTypes)
            {
                parts.Add(constraintType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
            }

            if (typeParameter.HasConstructorConstraint)
            {
                parts.Add("new()");
            }

            if (parts.Count > 0)
            {
                builder.Add($"{typeParameter.Name} : {string.Join(", ", parts)}");
            }
        }

        return builder.ToImmutable();
    }

    private sealed record TypeDeclarationInfo(
        string Name,
        string DisplayName,
        string Accessibility,
        string Keyword,
        string Modifiers,
        string TypeParameters,
        ImmutableArray<string> ConstraintClauses,
        bool IsPartial);

    private sealed record MapperTarget(
        string? Namespace,
        ImmutableArray<TypeDeclarationInfo> ContainingTypes,
        TypeDeclarationInfo TargetType,
        string MetadataPath,
        ImmutableArray<(ITypeSymbol Source, ITypeSymbol Dest)> Pairs,
        Diagnostic? Diagnostic);
}
